name: Integration Tests

permissions: read-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GOTOOLCHAIN: local

jobs:
  flag-parsing-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.26]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: ${{ matrix.go-version }}
    - run: go run cmd/auth/main.go | grep "Update your .netrc file to work with Google Cloud Artifact Registry Go Repositories."
    - run: go run cmd/auth/main.go --help | grep "Commands:"
    - run: go run cmd/auth/main.go bad-command | grep 'unknown command "bad-command"'
