name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GOTOOLCHAIN: local

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v3
      with:
        go-version: 1.26
    - name: gofmt
      run: gofmt -l ./ > gofmt.txt && ! [ -s gofmt.txt ]
    - name: vet
      run: go vet $(go list ./...) > govet.txt && ! [ -s govet.txt ]
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.25, 1.26]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test ./...
